### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by simkovic** [FoveHMD/SDK#1]
Is linux support planned? Personally, I'm just interested in getting data from the eyetracker and have no interest in your compositor, head tracking and other stuff. 

If not, do you plan to release the source code, so that linux users may easily figure out how to get data from the eyetracker?

**Comment by rodrigo-fove** [comment]
Hello simkovic!

Thank you for your comment. 

Yes, we are planning to support Linux in the future. However, the eye-tracking part of our SDK will continue to be closed source. We currently provide ample support for developers wishing to include eye-tracking in their VR applications through our API, although it sounds that you have a non-VR-specific usage in mind. We are happy to hear about your ideas and what application you are considering; possibly we can support your project directly. Email us at [mailto:projects@fove-inc.com].

By the way, we encourage you to post your question on our forums (http://forum.getfove.com/). We are closing this repo soon and moving software distribution to our website.

Cheers!
